export enum PaymentStoreSuccessEnum {
  PAYMENT_ADDED = "PAYMENT_ADDED",
  PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED",
  TRANSACTION_SUCCEEDED = "TRANSACTION_SUCCEEDED",
  PAYMENT_DENIED = "PAYMENT_DENIED",
}
