export enum WalletStoreSuccessEnum {
  WALLET_ADDED = "WALLET_ADDED",
  WALLET_PIN_CHANGED = "WALLET_PIN_CHANGED",
  WALLET_GUARDS_SET = "WALLET_GUARDS_SET",
  WALLET_SIGNERS_SET = "WALLET_SIGNERS_SET",
  WALLET_PENDING_GUARDS_SET = "WALLET_PENDING_GAURDS_SET",
  WALLET_PENDING_SIGNERS_SET = "WALLET_PENDING_SIGNERS_SET",
  WALLET_RECOVERY_INTIATED = "WALLET_RECOVERY_INTIATED",
}
