export enum ENSRegistrationStepsEnum {
  BEFORE_COMMIT = 'REGISTRATION.BEFORE_COMMIT',
  COMMIT_SENT = 'REGISTRATION.COMMIT_SENT',
  COMMIT_COMPLETE = 'REGISTRATION.COMMIT_COMPLETE',
  AWAIT = 'REGISTRATION.AWAIT',
  BEFORE_REGISTRATION = 'REGISTRATION.BEFORE_REGISTRATION',
  REGISTRATION_SENT = 'REGISTRATION.REGISTRATION_SENT',
  REGISTRATION_COMPLETE = 'REGISTRATION.REGISTRATION_COMPLETE',
}
