export enum PaymentStatusTypesEnum {
  UNKNOWN = "PAYMENT.STATUS_UNKNOWN",
  PENDING = "PAYMENT.PENDING",
  COMPLETED = "PAYMENT.COMPLETED",
  FAILED = "PAYMENT.FAILED",
  APPROVED = "PAYMENT.APPROVED",
  DECLINED = "PAYMENT.DECLINED",
  AWAITING_APPROVAL = "PAYMENT.AWAITING_APPROVAL",
}
