export enum PaymentTypeStringsEnum {
  PAYMENT_RECEIVED = "PAYMENT.PAYMENT_RECEIVED",
  PAYMENT_SENT = "PAYMENT.PAYMENT_SENT",
  SAVINGS_ADDED = "PAYMENT.SAVINGS_ADDED",
  SAVINGS_REDEEMED = "PAYMENT.SAVINGS_REDEEMED",
  CURRENCY_EXCHANGED = "PAYMENT.CURRENCY_EXCHANGED",
  WALLET_VERIFIED = "PAYMENT.WALLET_VERIFICATION",
  SET_GUARDS = "PAYMENT.SET_GUARDS",
  SET_SIGNERS = "PAYMENT.SET_SIGNERS",
  RECOVER_WALLET = "PAYMENT.RECOVER_WALLET",
  RECOVERY_APPROVAL_REQUESTED = "PAYMENT.RECOVERY_APPROVAL_REQUESTED",
  TRANSACTION_APPROVAL_REQUESTED = "PAYMENT.TRANSACTION_APPROVAL_REQUESTED",
  WITHDRAWN_FUNDS = "PAYMENT.WITHDRAWN_FUNDS",
}
