export enum RenewalDurationsEnum {
  '1WEEK' = 'RENEWAL_DURATIONS.ONE_WEEK',
  '1MONTH' = 'RENEWAL_DURATIONS.ONE_MONTH',
  '3MONTHS' = 'RENEWAL_DURATIONS.THREE_MONTHS',
  '6MONTHS' = 'RENEWAL_DURATIONS.SIX_MONTHS',
  '1YEAR' = 'RENEWAL_DURATIONS.ONE_YEAR',
  '2YEARS' = 'RENEWAL_DURATIONS.TWO_YEARS',
  '3YEARS' = 'RENEWAL_DURATIONS.THREE_YEARS',
  '4YEARS' = 'RENEWAL_DURATIONS.FOUR_YEARS',
  '5YEARS' = 'RENEWAL_DURATIONS.FIVE_YEARS',
}
