export enum RenewalDurationsTimeMultiplierEnum {
  'RENEWAL_DURATIONS.ONE_MONTH' = 0.0767,
  'RENEWAL_DURATIONS.THREE_MONTHS' = 0.2301,
  'RENEWAL_DURATIONS.SIX_MONTHS' = 0.5,
  'RENEWAL_DURATIONS.ONE_YEAR' = 1,
  'RENEWAL_DURATIONS.TWO_YEARS' = 2,
  'RENEWAL_DURATIONS.THREE_YEARS' = 3,
  'RENEWAL_DURATIONS.FOUR_YEARS' = 4,
  'RENEWAL_DURATIONS.FIVE_YEARS' = 5,
}
