export enum IpfsErrorsEnum {
  LOCAL_NODE_INIT_ERROR,
  SWARM_PEERS_UNRESOLVED,
  LOCAL_NODE_SUBSCRIPTION_TO_PEER_FAILED,
  REMOTE_NODE_SUBSCRIPTION_TO_PEER_FAILED,
  REMOTE_NODE_NOT_SUBSCRIBED,
  LOCAL_NODE_NOT_SUBSCRIBED,
  IPNS_NOT_RESOLVED_IN_PEER,
}
