export enum WalletStoreErrorsEnum {
	UNKNOWN = 'UNKNOWN_WALLET',
	RECOVERY_INVALID = 'RECOVERY_INVALID',
	PIN_INVALID = 'PIN_INVALID',
	OLD_PIN_INVALID = 'OLD_PIN_INVALID',
	NEW_PIN_INVALID = 'NEW_PIN_INVALID',
	QRSCANNER_CAMERA_NO_PERMISSION = 'QRSCANNER_CAMERA_NO_PERMISSION',
	QRSCANNED_RESULT_ERROR = 'QRSCANNED_RESULT_ERROR',
	QRSCAN_CANCELLED = 'QRSCAN_CANCELLED',
	SIGNING_PAYMENT_ERROR = 'SIGNING_PAYMENT_ERROR',
	QRSCANNED_WALLET_ADDRESS_INVALID = 'QRSCANNED_WALLET_ADDRESS_INVALID',
}
